### ISSUE TITLE
UnsatisfiedLinkError in BrotliStreamCompressor

### ISSUE THREAD

**Issue by mikolajpodbielski** [MeteoGroup/jbrotli#12]
When running this code

`new BrotliStreamCompressor();`

UnsatisfiedLinkError is thrown with following stack trace:

`Exception in thread "main" java.lang.UnsatisfiedLinkError: org.meteogroup.jbrotli.BrotliStreamCompressor.initJavaFieldIdCache()I
	at org.meteogroup.jbrotli.BrotliStreamCompressor.initJavaFieldIdCache(Native Method)
	at org.meteogroup.jbrotli.BrotliStreamCompressor.<clinit>(BrotliStreamCompressor.java:28)
	at xxx.Main.main(Main.java:59)`

Possible cause:
jbrotli-native/src/main/cpp/org_meteogroup_jbrotli_BrotliStreamCompressor.cxx line 45
native code is trying to get ID of field which does not exist.

**Comment by mikolajpodbielski** [comment]
I forgot to mention that I'm using jbrotli 0.5.0 with jbrotli-native-win32-x86-amd64 on Windows 10 64bit

**Comment by nitram509** [comment]
Hi,

when you run ```BrotliLibraryLoader.loadBrotli();```
before instantiating a new instance of ```new BrotliStreamCompressor();``` ?
Does this solve the issue?

Regards
Martin
